heat_template_version: 2016-04-08

parameter_groups:
- label: Cloud Network Settings
  parameters:
    - network
    - subnet

- label: Cloud Server Settings
  parameters:
    - nodeimage
    - nodeflavour
    - nodecount

parameters:
  network:
    label: Network Name
    description: Network Name for internode communications
    type: string
    default: GaleraNetwork
  
  subnet:
    label: Network Subnet
    description: Subnet used for the GaleraNetwork resources
    type: string
    default: 192.168.1.0/24

  nodecount:
    label: Number of Servers
    description: Number of GlusterFS nodes to create
    type: number
    default: 5
    constraints:
      - allowed_values: [ 3, 5, 7, 9, 11 ]
    description: Cluster must have an odd number of nodes.

  nodeflavour:
    label: Server Size
    description: |
      The size is based on the amount of RAM for the provisioned server.
    type: string
    default: 4 GB General Purpose v1
    constraints:
      - allowed_values:
        - 2 GB General Purpose v1
        - 4 GB General Purpose v1
        - 8 GB General Purpose v1
        - 15 GB I/O v1
        - 30 GB I/O v1
        - 60 GB I/O v1
        - 90 GB I/O v1
        - 120 GB I/O v1
        description: Must be a valid Nova Cloud Server flavor.

  nodeimage:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM) (Orchestration)
    constraints:
    - allowed_values:
      - CentOS 7 (PVHVM) (Orchestration)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM) (Orchestration)
      description: Must be a supported operating system

resources:
  galeranetwork:
    type: OS::Neutron::Net
    properties:
      name: { get_param: network }

  galerasubnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: galeranetwork }
      cidr: { get_param: subnet }

  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  galeranodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: nodecount }
      resource_def:
        type: https://raw.githubusercontent.com/0xdc/Heat-Orchestration-Examples/master/neutron_port_resourcegroup-childtemplate_v2.yaml
        properties:
          ssh_keypair_name: { get_resource: ssh_key }
          ssh_private_key:  { get_attr: [ssh_key, private_key] }
          nodeflavour:      { get_param: nodeflavour }
          nodeimage:        { get_param: nodeimage }
          stack_id:         { get_param: "OS::stack_id" }
          galera_network:   { get_resource: galeranetwork }
          galera_subnet:    { get_resource: galerasubnet }

outputs:
  galera_ips:
    value: { get_attr: [galeranodes, galeranode_ip] }
    description: "Galera Server IPs"
  
  galera_private_ips:
    value: { get_attr: [galeranodes, galeranode_private_ip]}
    description: "Galera servicenet IPs"
  
  ssh_key:
    description: "SSH Private Key"
    value: { get_attr: [ssh_key, private_key]}
  
  galera_isolated_ips:
    description: "Galera isolated IPs"
    value: { get_attr: [galeranodes, galeranode_isolated_ip]}
